coverage: 
  status:
    project:
      default: off
      harvester_test:
        target: auto
        flags:
          - harvester_test
          
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null
flags:
  harvester_test:
    paths:
      - src/Hercules.ED.HarvesterTest
    carryforward: false
