init:
  name: "edma-01"
  ##############################
  # storageClassName DE UNIVERISDAD DE MURCIA
  storageClassName: "nfs-client"
  #storageClassName: "ionos-enterprise-ssd"
  ##############################
  # DIFERENTES NAMESPACES
  namespace: "edma-hercules"
  ##############################
  # DIFERENTES POLITICAS DE PULL
  #pullpolicy: Always
  pullpolicy: IfNotPresent
  ##############################
  conecctionType: "2"
  idiomas: "es|Español,en|English"
  mulIdiomas: "es|Español,en|English,ca|Català,eu|Euskara,gl|Galego,fr|Français"
  replicaCount: 1
  secret: "regcred"
  serviceaccount: test-edma-hercules
  urlBase: "http://serviciosedma.gnoss.com"
  volumeClaimStorage02: "5Gi"
  volumeClaimStorage01: "30Gi"
  volNameState: "voledma"

servicios:
  nombreClusterIp: "servicios-gnoss"

ingress:
  class: "nginx"
  hostService: "serviciosedma.gnoss.com"
  hostWeb: "edma.gnoss.com"
  services: 80
  web: 80

serviciosWin:
  intervalo: "100"
  restartPolicy: Always

pvc:
  cargafuentesexternas1: "carfuente1-pvc"
  cargafuentesexternas2: "carfuente2-pvc"
  desnormalizador: "desnor-pvc"
  oauth: "compartido-pvc"
  rabbitconsume: "rabcons-pvc" 
  storage: "1Gi"

###########################
#                         #
#    VALUES PARA NGINX    #
#                         #
###########################

nginx:
  image: "gnoss/nginx"
  tag: "latest" 
  port1: 80
  port2: 8080
  nombreServicio: "serviciosedma"
  tipoServicio: "ClusterIP"
  protocolo: TCP

######################################
#                                    #
#     VALUES PARA BASES DE DATOS     #
#                                    #
######################################

postgres:
  image: "postgres"
  tag: "11.15"
  portSql: 5432
  targetPortSql: 5432
  cadenaConexionAcid: "Host=servicios-gnoss;Port=5432;Database=postgres;Username=postgres;Password=ApHSTCRBwX;Persist Security Info = true"
  cadenaConexionBase: "Host=servicios-gnoss;Port=5432;Database=postgres;Username=postgres;Password=ApHSTCRBwX;Persist Security Info = true"
  cadenaConexionOauth: "Host=servicios-gnoss;Port=5432;Database=postgres;Username=postgres;Password=ApHSTCRBwX;Persist Security Info = true"
  password: "ApHSTCRBwX"

virtuoso:
  image: "openlink/virtuoso-opensource-7"
  tag: "latest"
  password: "mysecret"
  portSparql: 8890
  targetPortSparql: 8890
  portIsql: 1111
  targetPortIsql: 1111
  cadenaConexion: "HOST=servicios-gnoss:1111;UID=dba;PWD=mysecret;Pooling=true;Max Pool Size=10;Connection Lifetime=15000"
  maxClientConnecction: "50"
  serverIdString: "virtuoso"
  xAnyNormalization: "3"
  dirsAllowed: ./dumps
  maxClientConnectionsVirt: "100"
  maxDirtyBuffers: "60000"
  numberOfBuffers: "100000"

redis:
  image: "redis"
  tag: "3.2-alpine"
  port: 6379
  targetPort: 6379
  redisBd: "2"
  redisTimeout: "60"
  recursosBd: "3"
  recursosTimeout: "60"
  liveusuariosBd: "2"
  liveusuariosTimeout: "60"

rabbitmq:
  cadenaConexion: "amqp://gnoss:gnoss1234@rabbitmq:5672/"
#  replicaCount: 1
#  volNameState: volrabbitmq
#  volumeClaimStorage: "5Gi"

oauthv3:
  ruta: "/app/Config/ConfigOAuth/"

###########################
#                         #
#     VALUES COMUNES      #
#                         #
###########################

valuesComunes:
  autoCompletar: "http://serviciosedma.gnoss.com/autocompletar/autocompletar"
  denormalizerQueueRabbit: "denormalizerEdmaQueue"
  dominio: "edma.gnoss.com"
  logPath: "/app/logs"
  urlArchivos: "http://archivo/"
  urlBaseEnriquecimiento: "http://herculesapi.elhuyar.eus"
  urlContent: "http://serviciosedma.gnoss.com/content"
  urlDocuments: "http://documents/GestorDocumental"
  urlEnriquecimiento: "http://herculesapi.elhuyar.eus"
  urlFacetas: "http://facetas/CargadorFacetas"
  urlFacetasExterno: "http://serviciosedma.gnoss.com/facetas/CargadorFacetas"
  urlInterno: "http://interno"
  urlLogin: "http://serviciosedma.gnoss.com/login"
  urlOauth: "http://oauth/"
  urlPublicacion: "http://publicationapi/"
  urlResultados: "http://resultados/CargadorResultados"
  urlResultadosExterno: "http://serviciosedma.gnoss.com/resultadosCargadorResultados"
  urlServiceInDomain: "login/"

######################################
#                                    #
#     VALUES PARA SERVICIOS WEB      #
#                                    #
######################################

facetas:
  replicas: 1
  image: "gnoss/facets"
  tag: "latest"
  port: 80
  restartPolicy: Always

web:
  replicas: 1
  image: "gnoss/web"
  tag: "latest"
  port: 80
  puertoSocketsOffline: "8245"
  connectionType: "2"
  https: "false"
  desplegadoDocker: "true"
  restartPolicy: Always

login:
  replicas: 1
  image: "gnoss/login"
  tag: "latest"
  port: 80
  restartPolicy: Always

resultados:
  replicas: 1
  image: "gnoss/results"
  tag: "latest"
  port: 80
  restartPolicy: Always

interno:
  replicas: 1
  image: "gnoss/intern"
  tag: "latest"
  port1: 80
  port2: 81
  restartPolicy: Always

archivo:
  replicas: 1
  image: "gnoss/ontologies"
  tag: "latest"
  port: 80
  rutaOntologias: "Ontologias/Archivos"
  restartPolicy: Always

documents:
  replicas: 1
  image: "gnoss/documents"
  tag: "latest"
  port: 80
  restartPolicy: Always

autocompletar:
  replicas: 1
  image: "gnoss/autocomplete"
  tag: "latest"
  port: 80
  restartPolicy: Always

despliegues:
  replicas: 1
  image: "gnoss/despliegues"
  tag: "latest"
  port: 80
  puertoSocketsOffline: "1745"
  connectionType: "2"  
  restartPolicy: Always

api:
  replicas: 1
  image: "gnoss/api"
  tag: "latest"
  port: 80
  puertoSocketsOffline: "1745"
  connectionType: "2"
  hilosAplicacion: "200"
  restartPolicy: Always

oauth:
  replicas: 1
  image: "gnoss/oauth"
  tag: "latest"
  port: 80
  puertoSocketsOffline: "1745"
  connectionType: "2"
  hilosAplicacion: "200"
  restartPolicy: Always
  
editorcv:
  replicas: 1
  image: "gnoss/edma-editorcv"
  tag: "latest"
  port: 80
  restartPolicy: Always
  urlImportadorExportador: "http://importadorcv"
  urlSgi: "https://sgi.demo.treelogic.com"
  usernameEsbCsp: "gestor-csp"
  passwordEsbCsp: "gestor-csp-2021"
  usernameEsbPrc: "gestor-prc"
  passwordEsbPrc: "gestor-prc-2021"
  maxMonthsValidationDocument: "36"
  maxMonthsValidationProjectsDocument: "36"

servicioexterno:
  replicas: 1
  image: "gnoss/edma-servicioexterno"
  tag: "latest"
  port: 80
  restartPolicy: Always
  queueRabbit: "fuentesExternasQueue"
  urlSimilarity: "http://herculesapi.elhuyar.eus/similarity/query_similar"
  
wosapi:
  replicas: 1
  image: "gnoss/edma-wosapi"
  tag: "latest"
  port: 80
  restartPolicy: Always
  
crossrefapi:
  replicas: 1
  image: "gnoss/edma-crossrefapi"
  tag: "latest"
  port: 80
  restartPolicy: Always

opencitationsapi:
  replicas: 1
  image: "gnoss/edma-opencitationsapi"
  tag: "latest"
  port: 80
  restartPolicy: Always

scopusapi:
  replicas: 1
  image: "gnoss/edma-scopusapi"
  tag: "latest"
  port: 80
  restartPolicy: Always

semanticscholarapi:
  replicas: 1
  image: "gnoss/edma-semanticscholarapi"
  tag: "latest"
  port: 80
  restartPolicy: Always

zenodoapi:
  replicas: 1
  image: "gnoss/edma-zenodoapi"
  tag: "latest"
  port: 80
  restartPolicy: Always
  urlZenodo: "https://zenodo.org/api/records/"

publicationapi:
  replicas: 1
  image: "gnoss/edma-publicationapi"
  tag: "latest"
  port: 80
  restartPolicy: Always
  urlZenodo: "http://zenodoapi/"
  urlSemanticScholar: "http://semanticscholarapi/"
  urlScopus: "http://scopusapi/"
  urlOpenCitations: "http://opencitationsapi/"
  urlCrossRef: "http://crossrefapi/"
  urlWos: "http://wosapi/"
  urlOpenAire: "http://openaireapi/"

figshareapi:
  replicas: 1
  image: "gnoss/edma-figshareapi"
  tag: "latest"
  port: 80
  restartPolicy: Always
  urlBase: "https://api.figshare.com/v2"
  token: ""

githubapi:
  replicas: 1
  image: "gnoss/edma-githubapi"
  tag: "latest"
  port: 80
  restartPolicy: Always
  urlBase: "https://api.github.com"

openaireapi:
  replicas: 1
  image: "gnoss/edma-openaireapi"
  tag: "latest"
  port: 80
  restartPolicy: Always
  urlOpenAire: "https://api.openaire.eu"

importadorcv:
  replicas: 1
  image: "gnoss/edma-importadorcv"
  tag: "latest"
  port: 80
  restartPolicy: Always
  usuario_PDF: "um01"
  PSS_PDF: "dcgp017SU8rq"

graphicengine:
  replicas: 1
  image: "gnoss/edma-graphicengine"
  tag: "latest"
  port: 80
  restartPolicy: Always

#######################################
#                                     #
#    VALUES PARA SERVICIOS WINDOWS    #
#                                     #
#######################################

# OLD_mail #
mail:
  image: gnoss/gnoss.backgroundtask.mail.opencore
  tag: 0.0.1_beta
  
# OLD_REFRESCO_CACHE #
cacherefresh:
  image: gnoss/gnoss.backgroundtask.cacherefresh.opencore
  tag: 0.0.1_beta
  conecctionType: "2"

# OLD_DEPLOYMENT_LIVE_USUARIOS #
communitywall:
  image: gnoss/gnoss.backgroundtask.communitywall.opencore
  tag: 0.0.1_beta

# OLD_REPARTO_COLAS #
distributor:
  image: gnoss/gnoss.backgroundtask.distributor.opencore
  tag: 0.0.1_beta

# OLD_BASE #
searchgraphgeneration:
  image: gnoss/gnoss.backgroundtask.searchgraphgeneration.opencore
  tag: 0.0.1_beta

# OLD_BASE_USUARIOS #
socialsearchgraphgeneration:
  image: gnoss/gnoss.backgroundtask.socialsearchgraphgeneration.opencore
  tag: 0.0.1_beta

# OLD_REFRESCO_CACHE_BANDEJA_MENSAJES #
socialcacherefresh:
  image: gnoss/gnoss.backgroundtask.socialcacherefresh.opencore
  tag: 0.0.1_beta

# OLD_LIVE_USUARIOS_ESPECIFICOS #
userwall:
  image: gnoss/gnoss.backgroundtask.userwall.opencore
  tag: 0.0.1_beta

# OLD_LIVE_EXTRA #
visitcluster:
  image: gnoss/gnoss.backgroundtask.visitcluster.opencore
  tag: 0.0.1_beta

# OLD_SOCKETS_OFFLINE #
visitregistry:
  image: gnoss/gnoss.backgroundtask.visitregistry.opencore
  tag: 0.0.1_beta
  port: 1745
  protocol: TCP

rabbitconsume:
  replicas: 1
  image: "gnoss/edma-rabbitconsume"
  tag: "latest"
  port: 80
  restartPolicy: Always
  queueRabbit: "fuentesExternasQueue"
  urlZenodo: "http://zenodoapi/"
  urlFigShare: "http://figshareapi/"
  urlGitHub: "http://githubapi/"
  directorioEscritura: "/app/logs/FileDatosOut/"
  path1: "/app/logs/FileDatosOut/"
  
desnormalizador:
  replicas: 1
  image: "gnoss/edma-desnormalizador"
  tag: "latest"
  port: 80
  restartPolicy: Always
  directorioEscritura: "/app/desnormalizador/"
  denormalizerCronExpression: "0 0 2 ? * *"
  path1: "/app/desnormalizador"

cargafuentesexternas:
  replicas: 1
  image: "gnoss/edma-cargafuentesexternas"
  tag: "latest"
  port: 80
  restartPolicy: Always
  directorioEscritura: "/app/logs/write/"
  directorioLectura: "/app/logs/read/"
  path1: "/app/logs/write/"
  path2: "/app/logs/read/"
