UPDATE DB.DBA.SYS_USERS SET U_ACCOUNT_DISABLED=0 WHERE U_NAME='SPARQL';
GRANT SPARQL_UPDATE TO "SPARQL";
GRANT EXECUTE ON DB.DBA.SPARQL_INSERT_QUAD_DICT_CONTENT TO "SPARQL";
GRANT EXECUTE ON DB.DBA.SPARQL_INSERT_QUAD_DICT_CONTENT TO "SPARQL_UPDATE";
GRANT EXECUTE ON DB.DBA.SPARQL_INSERT_DICT_CONTENT TO "SPARQL";
GRANT EXECUTE ON DB.DBA.L_O_LOOK_NE TO "SPARQL";
DB.DBA.RDF_DEFAULT_USER_PERMS_SET('SPARQL',3);