//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Export140
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cvnet.fecyt.es")]
    public partial class GenerarPDFWSException
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.cvnet.fecyt.es/xsd")]
    public partial class PdfGeneratorBean
    {
        
        private byte[] dataHandlerField;
        
        private string filenameField;
        
        private string returnCodeField;
        
        private int numPagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] dataHandler
        {
            get
            {
                return this.dataHandlerField;
            }
            set
            {
                this.dataHandlerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string returnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int numPages
        {
            get
            {
                return this.numPagesField;
            }
            set
            {
                this.numPagesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cvnet.fecyt.es", ConfigurationName="ServiceReference1.GenerarPDFWS")]
    public interface GenerarPDFWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cvnet.fecyt.es/GenerarPDFWS/crearPDFBeanBytesRequest", ReplyAction="http://ws.cvnet.fecyt.es/GenerarPDFWS/crearPDFBeanBytesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Export140.GenerarPDFWSException), Action="http://ws.cvnet.fecyt.es/GenerarPDFWS/crearPDFBeanBytes/Fault/GenerarPDFWSExcepti" +
            "on", Name="GenerarPDFWSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Export140.crearPDFBeanBytesResponse> crearPDFBeanBytesAsync(Export140.crearPDFBeanBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cvnet.fecyt.es/GenerarPDFWS/crearPDFBeanRequest", ReplyAction="http://ws.cvnet.fecyt.es/GenerarPDFWS/crearPDFBeanResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Export140.PdfGeneratorBean> crearPDFBeanAsync(string user, string passwd, string nameCVN, string sXmlIn, string tipoPlantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cvnet.fecyt.es/GenerarPDFWS/crearPDFBeanZipRequest", ReplyAction="http://ws.cvnet.fecyt.es/GenerarPDFWS/crearPDFBeanZipResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Export140.GenerarPDFWSException), Action="http://ws.cvnet.fecyt.es/GenerarPDFWS/crearPDFBeanZip/Fault/GenerarPDFWSException" +
            "", Name="GenerarPDFWSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Export140.crearPDFBeanZipResponse> crearPDFBeanZipAsync(Export140.crearPDFBeanZipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cvnet.fecyt.es/GenerarPDFWS/crearPDFBeanCvnRootBeanRequest", ReplyAction="http://ws.cvnet.fecyt.es/GenerarPDFWS/crearPDFBeanCvnRootBeanResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Export140.GenerarPDFWSException), Action="http://ws.cvnet.fecyt.es/GenerarPDFWS/crearPDFBeanCvnRootBean/Fault/GenerarPDFWSE" +
            "xception", Name="GenerarPDFWSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Export140.crearPDFBeanCvnRootBeanResponse> crearPDFBeanCvnRootBeanAsync(Export140.crearPDFBeanCvnRootBeanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cvnet.fecyt.es/GenerarPDFWS/crearPDFXmlBeanCvnRootBeanRequest", ReplyAction="http://ws.cvnet.fecyt.es/GenerarPDFWS/crearPDFXmlBeanCvnRootBeanResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Export140.GenerarPDFWSException), Action="http://ws.cvnet.fecyt.es/GenerarPDFWS/crearPDFXmlBeanCvnRootBean/Fault/GenerarPDF" +
            "WSException", Name="GenerarPDFWSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Export140.crearPDFXmlBeanCvnRootBeanResponse> crearPDFXmlBeanCvnRootBeanAsync(Export140.crearPDFXmlBeanCvnRootBeanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearPDFBeanBytes", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class crearPDFBeanBytesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nameCVN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] bXmlIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoPlantilla;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        public crearPDFBeanBytesRequest()
        {
        }
        
        public crearPDFBeanBytesRequest(string user, string passwd, string nameCVN, byte[] bXmlIn, string tipoPlantilla, string language)
        {
            this.user = user;
            this.passwd = passwd;
            this.nameCVN = nameCVN;
            this.bXmlIn = bXmlIn;
            this.tipoPlantilla = tipoPlantilla;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearPDFBeanBytesResponse", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class crearPDFBeanBytesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Export140.PdfGeneratorBean @return;
        
        public crearPDFBeanBytesResponse()
        {
        }
        
        public crearPDFBeanBytesResponse(Export140.PdfGeneratorBean @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearPDFBeanZip", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class crearPDFBeanZipRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nameCVN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] bXmlIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoPlantilla;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        public crearPDFBeanZipRequest()
        {
        }
        
        public crearPDFBeanZipRequest(string user, string passwd, string nameCVN, byte[] bXmlIn, string tipoPlantilla, string language)
        {
            this.user = user;
            this.passwd = passwd;
            this.nameCVN = nameCVN;
            this.bXmlIn = bXmlIn;
            this.tipoPlantilla = tipoPlantilla;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearPDFBeanZipResponse", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class crearPDFBeanZipResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Export140.PdfGeneratorBean @return;
        
        public crearPDFBeanZipResponse()
        {
        }
        
        public crearPDFBeanZipResponse(Export140.PdfGeneratorBean @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnCodeGroup))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnItemBean : CvnBean
    {
        
        private CvnAuthorBean[] cvnAuthorBeanField;
        
        private CvnBoolean[] cvnBooleanField;
        
        private CvnCodeGroup[] cvnCodeGroupField;
        
        private CvnDateDayMonthYear[] cvnDateDayMonthYearField;
        
        private CvnDateMonthYear[] cvnDateMonthYearField;
        
        private CvnDateYear[] cvnDateYearField;
        
        private CvnDouble[] cvnDoubleField;
        
        private CvnDuration[] cvnDurationField;
        
        private CvnEntityBean[] cvnEntityBeanField;
        
        private CvnExternalPKBean[] cvnExternalPKBeanField;
        
        private CvnFamilyNameBean[] cvnFamilyNameBeanField;
        
        private CvnPageBean[] cvnPageBeanField;
        
        private CvnPhoneBean[] cvnPhoneBeanField;
        
        private CvnPhotoBean[] cvnPhotoBeanField;
        
        private CvnRichText[] cvnRichTextField;
        
        private CvnString[] cvnStringField;
        
        private CvnTitleBean[] cvnTitleBeanField;
        
        private CvnVolumeBean[] cvnVolumeBeanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnAuthorBean", Order=0)]
        public CvnAuthorBean[] CvnAuthorBean
        {
            get
            {
                return this.cvnAuthorBeanField;
            }
            set
            {
                this.cvnAuthorBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnBoolean", Order=1)]
        public CvnBoolean[] CvnBoolean
        {
            get
            {
                return this.cvnBooleanField;
            }
            set
            {
                this.cvnBooleanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnCodeGroup", Order=2)]
        public CvnCodeGroup[] CvnCodeGroup
        {
            get
            {
                return this.cvnCodeGroupField;
            }
            set
            {
                this.cvnCodeGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnDateDayMonthYear", Order=3)]
        public CvnDateDayMonthYear[] CvnDateDayMonthYear
        {
            get
            {
                return this.cvnDateDayMonthYearField;
            }
            set
            {
                this.cvnDateDayMonthYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnDateMonthYear", Order=4)]
        public CvnDateMonthYear[] CvnDateMonthYear
        {
            get
            {
                return this.cvnDateMonthYearField;
            }
            set
            {
                this.cvnDateMonthYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnDateYear", Order=5)]
        public CvnDateYear[] CvnDateYear
        {
            get
            {
                return this.cvnDateYearField;
            }
            set
            {
                this.cvnDateYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnDouble", Order=6)]
        public CvnDouble[] CvnDouble
        {
            get
            {
                return this.cvnDoubleField;
            }
            set
            {
                this.cvnDoubleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnDuration", Order=7)]
        public CvnDuration[] CvnDuration
        {
            get
            {
                return this.cvnDurationField;
            }
            set
            {
                this.cvnDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnEntityBean", Order=8)]
        public CvnEntityBean[] CvnEntityBean
        {
            get
            {
                return this.cvnEntityBeanField;
            }
            set
            {
                this.cvnEntityBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnExternalPKBean", Order=9)]
        public CvnExternalPKBean[] CvnExternalPKBean
        {
            get
            {
                return this.cvnExternalPKBeanField;
            }
            set
            {
                this.cvnExternalPKBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnFamilyNameBean", Order=10)]
        public CvnFamilyNameBean[] CvnFamilyNameBean
        {
            get
            {
                return this.cvnFamilyNameBeanField;
            }
            set
            {
                this.cvnFamilyNameBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnPageBean", Order=11)]
        public CvnPageBean[] CvnPageBean
        {
            get
            {
                return this.cvnPageBeanField;
            }
            set
            {
                this.cvnPageBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnPhoneBean", Order=12)]
        public CvnPhoneBean[] CvnPhoneBean
        {
            get
            {
                return this.cvnPhoneBeanField;
            }
            set
            {
                this.cvnPhoneBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnPhotoBean", Order=13)]
        public CvnPhotoBean[] CvnPhotoBean
        {
            get
            {
                return this.cvnPhotoBeanField;
            }
            set
            {
                this.cvnPhotoBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnRichText", Order=14)]
        public CvnRichText[] CvnRichText
        {
            get
            {
                return this.cvnRichTextField;
            }
            set
            {
                this.cvnRichTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnString", Order=15)]
        public CvnString[] CvnString
        {
            get
            {
                return this.cvnStringField;
            }
            set
            {
                this.cvnStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnTitleBean", Order=16)]
        public CvnTitleBean[] CvnTitleBean
        {
            get
            {
                return this.cvnTitleBeanField;
            }
            set
            {
                this.cvnTitleBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnVolumeBean", Order=17)]
        public CvnVolumeBean[] CvnVolumeBean
        {
            get
            {
                return this.cvnVolumeBeanField;
            }
            set
            {
                this.cvnVolumeBeanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnAuthorBean : CvnBean
    {
        
        private CvnFamilyNameBean cvnFamilyNameBeanField;
        
        private string givenNameField;
        
        private string signatureField;
        
        private int signatureOrderField;
        
        private bool signatureOrderFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CvnFamilyNameBean CvnFamilyNameBean
        {
            get
            {
                return this.cvnFamilyNameBeanField;
            }
            set
            {
                this.cvnFamilyNameBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GivenName
        {
            get
            {
                return this.givenNameField;
            }
            set
            {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SignatureOrder
        {
            get
            {
                return this.signatureOrderField;
            }
            set
            {
                this.signatureOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SignatureOrderSpecified
        {
            get
            {
                return this.signatureOrderFieldSpecified;
            }
            set
            {
                this.signatureOrderFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnFamilyNameBean : CvnBean
    {
        
        private string firstFamilyNameField;
        
        private string secondFamilyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstFamilyName
        {
            get
            {
                return this.firstFamilyNameField;
            }
            set
            {
                this.firstFamilyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SecondFamilyName
        {
            get
            {
                return this.secondFamilyNameField;
            }
            set
            {
                this.secondFamilyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnVolumeBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnTitleBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnRichText))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnPhotoBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnPhoneBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnPageBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnExternalPKBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnEntityBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnDuration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnDouble))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnDateYear))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnDateMonthYear))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnDateDayMonthYear))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnBoolean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnFamilyNameBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnAuthorBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnItemBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnCodeGroup))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnBean
    {
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnVolumeBean : CvnBean
    {
        
        private string numberField;
        
        private string volumeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Volume
        {
            get
            {
                return this.volumeField;
            }
            set
            {
                this.volumeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnTitleBean : CvnBean
    {
        
        private string identificationField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnRichText))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnString : CvnBean
    {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnRichText : CvnString
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnPhotoBean : CvnBean
    {
        
        private string bytesInBase64Field;
        
        private string mimeTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BytesInBase64
        {
            get
            {
                return this.bytesInBase64Field;
            }
            set
            {
                this.bytesInBase64Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnPhoneBean : CvnBean
    {
        
        private string extensionField;
        
        private string internationalCodeField;
        
        private string numberField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InternationalCode
        {
            get
            {
                return this.internationalCodeField;
            }
            set
            {
                this.internationalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnPageBean : CvnBean
    {
        
        private string finalPageField;
        
        private string initialPageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FinalPage
        {
            get
            {
                return this.finalPageField;
            }
            set
            {
                this.finalPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InitialPage
        {
            get
            {
                return this.initialPageField;
            }
            set
            {
                this.initialPageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnExternalPKBean : CvnBean
    {
        
        private string typeField;
        
        private string valueField;
        
        private string othersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Others
        {
            get
            {
                return this.othersField;
            }
            set
            {
                this.othersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnEntityBean : CvnBean
    {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnDuration : CvnBean
    {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnDouble : CvnBean
    {
        
        private double valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnDateYear : CvnBean
    {
        
        private System.DateTime valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnDateMonthYear : CvnBean
    {
        
        private System.DateTime valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnDateDayMonthYear : CvnBean
    {
        
        private System.DateTime valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnBoolean : CvnBean
    {
        
        private bool valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnCodeGroup : CvnItemBean
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearPDFBeanCvnRootBean", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class crearPDFBeanCvnRootBeanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nameCVN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://codes.cvn.fecyt.es/beans", IsNullable=false)]
        public ImportadorWebCV.CvnItemBean[] cvnRootBean;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoPlantilla;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        public crearPDFBeanCvnRootBeanRequest()
        {
        }
        
        public crearPDFBeanCvnRootBeanRequest(string user, string passwd, string nameCVN, ImportadorWebCV.CvnItemBean[] cvnRootBean, string tipoPlantilla, string language)
        {
            this.user = user;
            this.passwd = passwd;
            this.nameCVN = nameCVN;
            this.cvnRootBean = cvnRootBean;
            this.tipoPlantilla = tipoPlantilla;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearPDFBeanCvnRootBeanResponse", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class crearPDFBeanCvnRootBeanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Export140.PdfGeneratorBean @return;
        
        public crearPDFBeanCvnRootBeanResponse()
        {
        }
        
        public crearPDFBeanCvnRootBeanResponse(Export140.PdfGeneratorBean @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearPDFXmlBeanCvnRootBean", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class crearPDFXmlBeanCvnRootBeanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nameCVN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cvnRootBean;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoPlantilla;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        public crearPDFXmlBeanCvnRootBeanRequest()
        {
        }
        
        public crearPDFXmlBeanCvnRootBeanRequest(string user, string passwd, string nameCVN, string cvnRootBean, string tipoPlantilla, string language)
        {
            this.user = user;
            this.passwd = passwd;
            this.nameCVN = nameCVN;
            this.cvnRootBean = cvnRootBean;
            this.tipoPlantilla = tipoPlantilla;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearPDFXmlBeanCvnRootBeanResponse", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class crearPDFXmlBeanCvnRootBeanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Export140.PdfGeneratorBean @return;
        
        public crearPDFXmlBeanCvnRootBeanResponse()
        {
        }
        
        public crearPDFXmlBeanCvnRootBeanResponse(Export140.PdfGeneratorBean @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface GenerarPDFWSChannel : Export140.GenerarPDFWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GenerarPDFWSClient : System.ServiceModel.ClientBase<Export140.GenerarPDFWS>, Export140.GenerarPDFWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GenerarPDFWSClient() : 
                base(GenerarPDFWSClient.GetDefaultBinding(), GenerarPDFWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.GenerarPDFWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenerarPDFWSClient(EndpointConfiguration endpointConfiguration) : 
                base(GenerarPDFWSClient.GetBindingForEndpoint(endpointConfiguration), GenerarPDFWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenerarPDFWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GenerarPDFWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenerarPDFWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GenerarPDFWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenerarPDFWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Export140.crearPDFBeanBytesResponse> Export140.GenerarPDFWS.crearPDFBeanBytesAsync(Export140.crearPDFBeanBytesRequest request)
        {
            return base.Channel.crearPDFBeanBytesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Export140.crearPDFBeanBytesResponse> crearPDFBeanBytesAsync(string user, string passwd, string nameCVN, byte[] bXmlIn, string tipoPlantilla, string language)
        {
            Export140.crearPDFBeanBytesRequest inValue = new Export140.crearPDFBeanBytesRequest();
            inValue.user = user;
            inValue.passwd = passwd;
            inValue.nameCVN = nameCVN;
            inValue.bXmlIn = bXmlIn;
            inValue.tipoPlantilla = tipoPlantilla;
            inValue.language = language;
            return ((Export140.GenerarPDFWS)(this)).crearPDFBeanBytesAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<Export140.PdfGeneratorBean> crearPDFBeanAsync(string user, string passwd, string nameCVN, string sXmlIn, string tipoPlantilla)
        {
            return base.Channel.crearPDFBeanAsync(user, passwd, nameCVN, sXmlIn, tipoPlantilla);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Export140.crearPDFBeanZipResponse> Export140.GenerarPDFWS.crearPDFBeanZipAsync(Export140.crearPDFBeanZipRequest request)
        {
            return base.Channel.crearPDFBeanZipAsync(request);
        }
        
        public System.Threading.Tasks.Task<Export140.crearPDFBeanZipResponse> crearPDFBeanZipAsync(string user, string passwd, string nameCVN, byte[] bXmlIn, string tipoPlantilla, string language)
        {
            Export140.crearPDFBeanZipRequest inValue = new Export140.crearPDFBeanZipRequest();
            inValue.user = user;
            inValue.passwd = passwd;
            inValue.nameCVN = nameCVN;
            inValue.bXmlIn = bXmlIn;
            inValue.tipoPlantilla = tipoPlantilla;
            inValue.language = language;
            return ((Export140.GenerarPDFWS)(this)).crearPDFBeanZipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Export140.crearPDFBeanCvnRootBeanResponse> Export140.GenerarPDFWS.crearPDFBeanCvnRootBeanAsync(Export140.crearPDFBeanCvnRootBeanRequest request)
        {
            return base.Channel.crearPDFBeanCvnRootBeanAsync(request);
        }
        
        public System.Threading.Tasks.Task<Export140.crearPDFBeanCvnRootBeanResponse> crearPDFBeanCvnRootBeanAsync(string user, string passwd, string nameCVN, ImportadorWebCV.CvnItemBean[] cvnRootBean, string tipoPlantilla, string language)
        {
            Export140.crearPDFBeanCvnRootBeanRequest inValue = new Export140.crearPDFBeanCvnRootBeanRequest();
            inValue.user = user;
            inValue.passwd = passwd;
            inValue.nameCVN = nameCVN;
            inValue.cvnRootBean = cvnRootBean;
            inValue.tipoPlantilla = tipoPlantilla;
            inValue.language = language;
            return ((Export140.GenerarPDFWS)(this)).crearPDFBeanCvnRootBeanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Export140.crearPDFXmlBeanCvnRootBeanResponse> Export140.GenerarPDFWS.crearPDFXmlBeanCvnRootBeanAsync(Export140.crearPDFXmlBeanCvnRootBeanRequest request)
        {
            return base.Channel.crearPDFXmlBeanCvnRootBeanAsync(request);
        }
        
        public System.Threading.Tasks.Task<Export140.crearPDFXmlBeanCvnRootBeanResponse> crearPDFXmlBeanCvnRootBeanAsync(string user, string passwd, string nameCVN, string cvnRootBean, string tipoPlantilla, string language)
        {
            Export140.crearPDFXmlBeanCvnRootBeanRequest inValue = new Export140.crearPDFXmlBeanCvnRootBeanRequest();
            inValue.user = user;
            inValue.passwd = passwd;
            inValue.nameCVN = nameCVN;
            inValue.cvnRootBean = cvnRootBean;
            inValue.tipoPlantilla = tipoPlantilla;
            inValue.language = language;
            return ((Export140.GenerarPDFWS)(this)).crearPDFXmlBeanCvnRootBeanAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GenerarPDFWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GenerarPDFWSPort))
            {
                return new System.ServiceModel.EndpointAddress("https://integraciones.cvnet.es/generadorPdfWS_v1_4/services/GenerarPDFWS");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GenerarPDFWSClient.GetBindingForEndpoint(EndpointConfiguration.GenerarPDFWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GenerarPDFWSClient.GetEndpointAddress(EndpointConfiguration.GenerarPDFWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            GenerarPDFWSPort,
        }
    }
}
