apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: "edma-hercules"
type: Opaque
data:
  username: <INSERTA AQUI TU USERNAME CODIFICADO EN BASE64>
  password: <INSERTA AQUI TU PASSWORD CODIFICADO EN BASE64>
  cookie: ZWRtYS1yYWJiaXQ=
