name: Build and test Harvester_Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build src/Hercules.ED.HarvesterTest
    - name: Test
      run: dotnet test --collect:"XPlat Code Coverage" src/Hercules.ED.HarvesterTest
    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@239febf655bba88b16ff5dea1d3135ea8663a1f9
      uses: codecov/codecov-action@v1.0.15
      with:
        # User defined upload name. Visible in Codecov UI
        # name: # optional
        # Repository upload token - get it from codecov.io. Required only for private repositories
        # token: e5277ec5-491c-435b-ad01-1883e35fb366
        # Path to coverage file to upload
        # file: XUnitTestUrisFactory/TestResults
        # Comma-separated list of files to upload
        # file: coverage.cobertura.xml
        # files: # optional
        # Directory to search for coverage reports.
        directory: src/Hercules.ED.HarvesterTest
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        # flags: # optional
        flags: harvester_test
        # Write upload file to path before uploading
        # path_to_write_report: # optional
        # Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
        # env_vars: # optional
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        # fail_ci_if_error: # optional
        # Specify whether the Codecov output should be verbose
        # verbose: # optional
